---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# citoMove

The goal of citoMove is to provide an user-friendly R package for analyzing movement data with DNNs.

## Installation

You can install the development version of citoMove from [GitHub](https://github.com/) via:

```{r, eval = F}
# install.packages("devtools")
devtools::install_github("citoverse/citoMove")
```

# Examples

## One animal


```{r}
library(amt)
library(citoMove)
library(terra)
```

First we create a new covariate: the distance to the next forest. 

```{r}
forest <- amt::get_sh_forest()
forest <- terra::subst(forest, 0, NA)
forest_dist <- distance(forest)
names(forest_dist) <- "forest_dist"
plot(forest_dist)
```

Then we load the tracking data of one red deer. 

```{r}
data(deer)
dat_ssf <- deer |> 
  steps_by_burst() |> 
  random_steps() |> 
  extract_covariates(forest_dist) |> 
  time_of_day()
```

And fit a deep neural network (dnn): 

```{r}
model = dnn_ssf(case_ ~ forest_dist, data = dat_ssf, epoch = 200L, plot = FALSE, verbose = FALSE)
summary(model)
```
